spring:
  application:
    name: content-analysis-service

  ai:
    ollama:
      chat:
        options:
          model: "gpt-oss"

jina:
  url: "https://r.jina.ai"
  api-key: ""

serpapi:
  url: "https://serpapi.com"
  limit: 10
  api-key: ""