spring:
  application:
    name: content-analysis-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5431/content-analysis-service-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create

  ai:
    ollama:
      chat:
        options:
          model: "gpt-oss"

logging:
  logstash:
    server: "localhost:5000"
  level:
    org.springframework.security: DEBUG

jina:
  url: "https://r.jina.ai"

serpapi:
  url: "https://serpapi.com"
  limit: 1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics