spring:
  application:
    name: content-analysis-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/content-analysis-service-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create

  ai:
    ollama:
      chat:
        options:
          model: "gpt-oss"

jina:
  url: "https://r.jina.ai"

serpapi:
  url: "https://serpapi.com"
  limit: 2
