services:

  content-analysis-service:
    build:
      context: content-analysis-service
    image: content-analysis-service:latest
    deploy:
      replicas: 2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://content-analysis-service-db:5431/content-analysis-service-db
      - SPRING_RABBITMQ_HOST=rabbitmq
      - LOGGING_LOGSTASH_SERVER=logstash:5000
    networks:
      - wiarygodnik
      - elk_network
    depends_on:
      - content-analysis-service-db
      - rabbitmq

  content-analysis-service-db:
    image: postgres:15
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: content-analysis-service-db
    volumes:
      - content-analysis-service-db:/var/lib/postgresql/data
    networks:
      - wiarygodnik

  report-generation-service:
    build:
      context: report-generation-service
    image: report-generation-service:latest
    deploy:
      replicas: 2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://report-generation-service-db:5432/report-generation-service-db
      - SPRING_RABBITMQ_HOST=rabbitmq
      - LOGGING_LOGSTASH_SERVER=logstash:5000
    networks:
      - wiarygodnik
      - elk_network
    depends_on:
      - report-generation-service-db
      - rabbitmq

  report-generation-service-db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: report-generation-service-db
    volumes:
      - report-generation-service-db:/var/lib/postgresql/data
    networks:
      - wiarygodnik

  credibility-service:
    build:
      context: CredabilityService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - credibility-db
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://credibility-db:5432/credibility
      - SPRING_RABBITMQ_HOST=rabbitmq
      - LOGGING_LOGSTASH_SERVER=logstash:5000
    networks:
      - wiarygodnik
      - elk_network

  credibility-db:
    image: postgres:15
    container_name: credibility-db
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credibility
    volumes:
      - postgres_data_credibility:/var/lib/postgresql/data
    networks:
      - wiarygodnik

  content-fetcher-service:
    build:
      context: ./ContentFetcher/content_fetcher
      dockerfile: Dockerfile
    env_file:
      - ./ContentFetcher/content_fetcher/.env
    depends_on:
      - content-fetcher-db
      - rabbitmq
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8080"
    ports:
      - "8090:8080"
    networks:
      - wiarygodnik
      - elk_network

  content-fetcher-db:
    image: postgres:17
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: wiarygodnik
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: contentfetcherdb
    volumes:
      - contentfetcherpgdata:/var/lib/postgresql/data
    networks:
      - wiarygodnik

  rabbitmq:
    image: rabbitmq:4.2.1
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - wiarygodnik

  load-balancer:
    image: nginx:latest
    ports:
      - "3000:3000"
    volumes:
      - ./load-balancer/conf.d:/etc/nginx/conf.d
    networks:
      - wiarygodnik
    depends_on:
      - content-analysis-service

  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - start-dev
    ports:
      - "8888:8080"
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-db:/var/lib/postgresql/data

volumes:
  content-analysis-service-db:
  report-generation-service-db:
  keycloak-db:
  postgres_data_credibility:
  contentfetcherpgdata:

networks:
  wiarygodnik:
    driver: bridge
  elk_network:
    external: true
