services:

  report-service:
    build:
      context: report-service
    image: report-service:latest
    deploy:
      replicas: 2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://report-db:5432/report-db
      - SPRING_RABBITMQ_HOST=rabbitmq
      - LOGGING_LOGSTASH_SERVER=logstash:5000
    networks:
      - wiarygodnik
      - elk_network
    depends_on:
      - report-db
      - rabbitmq

  report-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: report-db
    volumes:
      - report-db:/var/lib/postgresql/data
    networks:
      - wiarygodnik

  credibility-service:
    build:
      context: CredabilityService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - credibility-db
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://credibility-db:5432/credibility
      - SPRING_RABBITMQ_HOST=rabbitmq
      - LOGGING_LOGSTASH_SERVER=logstash:5000
    networks:
      - wiarygodnik
      - elk_network

  credibility-db:
    image: postgres:15
    container_name: credibility-db
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credibility
    volumes:
      - postgres_data_credibility:/var/lib/postgresql/data
    networks:
      - wiarygodnik

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - wiarygodnik

  load-balancer:
    image: nginx:latest
    ports:
      - "3000:3000"
    volumes:
      - ./load-balancer/conf.d:/etc/nginx/conf.d
    networks:
      - wiarygodnik
    depends_on:
      - report-service

volumes:
  postgres_data_credibility:
  report-db:

networks:
  wiarygodnik:
    driver: bridge
  elk_network:
    external: true
